// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBvvvtG6gZz8HckfOOJswN21QtmwpusDE8',
    appId: '1:819722583382:web:4427633dd1c01d26302af7',
    messagingSenderId: '819722583382',
    projectId: 'notekey-58325',
    authDomain: 'notekey-58325.firebaseapp.com',
    storageBucket: 'notekey-58325.firebasestorage.app',
    measurementId: 'G-Z3KXYJJRZS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCWduzzXd0xEVBd1QOJj9gU201zDMXO4XU',
    appId: '1:819722583382:android:392e9c6cc08fbe5f302af7',
    messagingSenderId: '819722583382',
    projectId: 'notekey-58325',
    storageBucket: 'notekey-58325.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCxLuzOCq6_LCCJYO1ZD4Zy444V4Zd929M',
    appId: '1:819722583382:ios:649bbbc5d074ac6a302af7',
    messagingSenderId: '819722583382',
    projectId: 'notekey-58325',
    storageBucket: 'notekey-58325.firebasestorage.app',
    iosBundleId: 'com.example.notekeyApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCxLuzOCq6_LCCJYO1ZD4Zy444V4Zd929M',
    appId: '1:819722583382:ios:649bbbc5d074ac6a302af7',
    messagingSenderId: '819722583382',
    projectId: 'notekey-58325',
    storageBucket: 'notekey-58325.firebasestorage.app',
    iosBundleId: 'com.example.notekeyApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBvvvtG6gZz8HckfOOJswN21QtmwpusDE8',
    appId: '1:819722583382:web:bbebd9a7bd84fc29302af7',
    messagingSenderId: '819722583382',
    projectId: 'notekey-58325',
    authDomain: 'notekey-58325.firebaseapp.com',
    storageBucket: 'notekey-58325.firebasestorage.app',
    measurementId: 'G-VYG7YPMSNT',
  );
}
